version: 2
jobs:
  build:
    docker:
      - image: pandoc/latex:latest
    steps:
      - checkout
      - run:
          name: Build PDF
          command: /usr/local/bin/pandoc -f markdown+implicit_figures -s -o openacc-guide.pdf ??-*.markdown --citeproc --highlight-style pygments --top-level-division=chapter  -V geometry:letterpaper
      - store_artifacts:
          path: openacc-guide.pdf
workflows:
  version: 2
  build:
    jobs:
      - build
